# Generated by Django 5.2.1 on 2025-05-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedclient',
            name='connected_at',
        ),
        migrations.AddField(
            model_name='connectedclient',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedclient',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connectedclient',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
